### ISSUE TITLE
Custom MAVLink Message CRC Issue

### ISSUE THREAD

**Issue by fhgrderungs** [asv-soft/asv-mavlink#36] opened 2023-11-01 12:00 UTC
I have the following custom message:

```xml
<?xml version="1.0"?>

<mavlink>
  <include>common.xml</include>
  <messages>
    <message id="14202" name="CHEMICAL_DETECTOR_DATA">
		<description>Chemical Detector Data</description>
		<field type="uint32_t" name="agent_id">Agent ID, 0=No agent, 1=GA, 2=GB, 3=GD/GF, 4=VX, 5=VXR, 6=DPM, 7=AC/CK, 8=CK, 9=AC, 11=HD</field>
		<field type="float" name="concentration" units="mg/m3">Concentration (mg/m3), IEEE floating point format</field>
		<field type="uint32_t" name="bars">Bars (0 - 8)</field>
		<field type="uint32_t" name="bars_peak">Peak Bars (0 - 8)</field>
		<field type="float" name="dose" units="mg-min/m3">Dose (mg-min/m3), IEEE floating point format</field>
		<field type="float" name="hazard_level">Hazard Level - none, low, medium, high ( 0-3 )</field>
    </message>
  </messages>
</mavlink>
```

Now when I send that message like this with all values 0 (zero):

```csharp
var packet = new ChemicalDetectorDataPacket();
packet.SystemId = 1;
packet.ComponentId = 1;
packet.Payload.AgentId = 0;
packet.Payload.Concentration = 0;
packet.Payload.Bars = 0;
packet.Payload.BarsPeak = 0;
packet.Payload.Dose = 0;
packet.Payload.HazardLevel = 0;

await _mavlinkConnection.Send(packet, CancellationToken.None);
```

then I get a CRC Error:
```
Error for deserialize mavlink V2 package with messageID 14202: Bad X25Crc: want 13216, got 51630
```

If I change all FLOAT fields to, for example, -1 then it works fine:
```csharp
var packet = new ChemicalDetectorDataPacket();
packet.SystemId = 1;
packet.ComponentId = 1;
packet.Payload.AgentId = 0;
packet.Payload.Concentration = -1f;
packet.Payload.Bars = 0;
packet.Payload.BarsPeak = 0;
packet.Payload.Dose = -1f;
packet.Payload.HazardLevel = -1f;

await _mavlinkConnection.Send(packet, CancellationToken.None);
```

All Mavlink Sender / Receiver use `<PackageReference Include="Asv.Mavlink" Version="3.4.1" />`

Do you have an idea whats wrong here?

**Comment by asvol** [comment] 2023-11-02 06:21
I tryed to reproduce this bug:

1. Created a dialect [unit_test_message.xml](https://github.com/asv-soft/asv-mavlink/blob/b1f792dad5f278c18eb41c7f921e9b3cf4aa72ed/src/Asv.Mavlink/Protocol/Dialects/)

2. Generated C# messages by Asv.Mavlink.Shell.exe [unit_test_message.cs](https://github.com/asv-soft/asv-mavlink/blob/b1f792dad5f278c18eb41c7f921e9b3cf4aa72ed/src/Asv.Mavlink/Protocol/Messages/unit_test_message.cs)

3. Created two tests for thes messages Test_custom_crc_message() and Test_custom_crc_message2() 

4. All tests work fine and I can't reproduce (MavlinkPackets.cs)[https://github.com/asv-soft/asv-mavlink/blob/b1f792dad5f278c18eb41c7f921e9b3cf4aa72ed/src/Asv.Mavlink.Test/MavlinkPackets.cs]

5. It's working fine. Can't reproduce this bug.



I think this error occurred when the field name or type was changed and you forgot to regenerate C# code.
When the MAVLink code generator runs, it takes a checksum of the XML structure for each message and creates CRC_EXTRA field.
A CRC_EXTRA byte is added to the message checksum. A receiver can use this to confirm that it is compatible with the payload message format/definition. You can read about it [here](https://mavlink.io/en/guide/serialization.html#crc_extra)

If you reproduce this bug, we'd be happy to help.

**Comment by fhgrderungs** [comment] 2023-11-02 08:03
Thank you for your time trying to reproduce.

I can assure you that the C# Code was properly regenerated. In fact, the fields never changed. I think it has to do with MAVLink 2 Payload Truncation (https://mavlink.io/en/guide/serialization.html#payload_truncation) since it only happens when the payload, or at least the last part, is zero.

There are so many other MAVLink Applications in between the Sender (Drone) and Receiver (Notebook) for example:

- Multiple MAVLink Routers (one of them is custom built for Android)
- Herelink Controller
- MAVLink Reverse Proxy
- ...

So its very much possible that the issue is somewhere there. For now what I did is add an additional uint_8 field to the end of every message that I always set to 0xFF so the payload does not get truncated. It's a workaround and a bit ugly but it works.

But what confused me is that it only happens with my custom messages which are the ones sent by asv-mavlink. All other messages like ATTITUDE, GLOBAL_POSITION_INT and so on which come directly from the drone have never had a CRC error.

I can live with that workaround for now. If you dont have any more ideas we can close this issue.

And again, thanks for your awesome work with this lib.

**Comment by asvol** [comment] 2023-11-02 11:26
I don't think we need to close this issue. It is necessary to solve it (especially if problem in truncation at our side). Are you able to provide the data from the message in raw form (e.g. byte array)? I'll try to check it.

P.S. This library is being developed as part of the open source uav control program [Asv.Drones](https://github.com/asv-soft/asv-drones). It supports plugins, and you can add functionality for your payload ;)

**Comment by fhgrderungs** [comment] 2023-11-02 12:07
I can provide you with raw data but it takes some time.

I will take a look at `Asv.Drones`. Does it support multiple drones (swarm? 1 udp connection per drone). 
We currently have our own implementation of a ground station software as part of a research project which is web based. For telemetry we convert MAVLink Messages to MQTT so we can broadcast to multiple clients (eg. multiple user have the webpage open). The most challenging part is visualizing multiple drones and telemetry data (for example compass, attitude ...) in a single view. A big part is also creating a rich map with measurement data. (Each drone is equipped with a different sensor)

If you want I can provide you with more information about our project and the possiblity to maybe merge our features into Asv.Drones. Then we could also contribute further features directly into that.

**Comment by asvol** [comment] 2023-11-04 09:37
I'd be interested to learn more about your project.

Yes, we support multiple UAVs simultaneously, and we also enable command mode control, allowing multiple operators to simultaneously monitor and control one or several UAVs.

In our software, we have implemented a Mavlink packet router, and you can connect multiple ports.
Types of ports include: TCP_CLIENT, TCP_SERVER, UDP, SERIAL.

![image](https://github.com/asv-soft/asv-mavlink/assets/1770739/6c20304a-a613-4c4c-a6ce-cd2726949a3e)

**Comment by asvol** [comment] 2023-11-04 09:47
We have also implemented a ground service for the base communication station, which can route Mavlink packets.

In our case, it's a separate device to which operators connect from laptops or tablets via WiFi, and it communicates with UAVs through modems. This is convenient because it can be placed outdoors on a tripod, allowing operators to control the UAVs from a more comfortable location or remotely over the Internet.

![image](https://github.com/asv-soft/asv-mavlink/assets/1770739/3b420b77-dd30-4150-82a8-3e4725f5a684)

**Closed** 2024-10-14 12:28 UTC
Labels: bug, cannot reproduce
